version: '3'
services:
  web:
    image: registry.gitlab.com/job-insights-project/job-insights-devops/backend:1.0 
    container_name: my-django-app
    ports:
      - "8000:8000"  # Map the host port to the container port
    networks:
      - my-django-network  # Create a custom bridge network

  nginx:
    image: nginx
    container_name: my-nginx
    ports:
      - "80:80"  # Map the host port to the container port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx config file
    depends_on:
      - web
    networks:
      - my-django-network

networks:
  my-django-network:
    driver: bridge
