# Generated by Django 4.2.5 on 2023-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_interaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
