# Generated by Django 4.2.5 on 2023-10-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_userprofile_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
